-- stg 75张表
alter  table stg.stg_cccc_erms_base_pub_assetsinfo_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_base_equ_boatinfo_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_base_equ_mechaninfo_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_base_equ_tech_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_year_planedit_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_year_amountdet_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_year_apply_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_year_apply2plan_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_month_amountdet_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_year_plan_supply_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_proapply_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_proapply_chil_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_pro_relation_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_proapply_approval_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_progress_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_postevaluation_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_master_rentalequip_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_use_maintenance_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_use_entry_exit_info_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_use_construction_info_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_use_construction_day_info_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_handle_dis_disposal_infor_account_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_handle_dis_equ_disposal_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_handle_dis_apply_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_handle_dis_apply_equ_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_out_lease_apply_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_out_lease_apply_relation_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_out_settle_info_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_out_lease_list_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_own_test_detection_equipment_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_equip_type_mapping_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_own_fixed_assets_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_own_depr_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_own_state_change_his_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_own_certificate_his_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_waf_core_attach_info_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_em_system_appcountinfo_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_em_system_appcount_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_deploy_dispatch_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_deploy_dispatch_equ_information_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_deploy_apply_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_deploy_apply_equ_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_ge_bytearray_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_ge_property_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_hi_actinst_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_hi_attachment_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_hi_comment_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_hi_detail_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_hi_identitylink_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_hi_procinst_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_hi_taskinst_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_hi_varinst_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_id_group_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_id_info_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_id_membership_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_id_user_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_procdef_relation_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_re_deployment_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_re_model_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_re_procdef_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_ru_event_subscr_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_ru_execution_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_ru_identitylink_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_ru_job_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_procdef_info_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_ru_task_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_ru_variable_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_act_task_opinion_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_waf_core_dict_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_waf_core_dictitem_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_waf_ac_organ_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_base_equ_subpack_i_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_invm_plan_yeartime_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_waf_ac_organ2biz_f_d drop partition (etl_date <= '${etl_date}');
alter  table stg.stg_cccc_erms_zmdgs_actorginf_f_d drop partition (etl_date <= '${etl_date}');




-- ods 75张表
alter  table ods.ods_cccc_erms_base_pub_assetsinfo_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_base_equ_boatinfo_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_base_equ_mechaninfo_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_invm_plan_year_planedit_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_invm_plan_year_apply_i_d drop partition (end_date <= '${etl_date}');
truncate  table ods.ods_cccc_erms_invm_plan_year_apply2plan_f_d ;
truncate  table ods.ods_cccc_erms_invm_plan_month_amountdet_f_d ;
alter  table ods.ods_cccc_erms_invm_plan_year_plan_supply_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_invm_plan_proapply_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_invm_plan_proapply_chil_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_invm_proapply_approval_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_invm_plan_progress_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_invm_plan_postevaluation_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_master_rentalequip_i_d drop partition (end_date <= '${etl_date}');
truncate  table ods.ods_cccc_erms_use_maintenance_f_d ;
alter  table ods.ods_cccc_erms_use_entry_exit_info_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_use_construction_info_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_use_construction_day_info_i_d drop partition (end_date <= '${etl_date}');
truncate  table ods.ods_cccc_erms_handle_dis_disposal_infor_account_f_d ;
truncate  table ods.ods_cccc_erms_handle_dis_equ_disposal_f_d;
alter  table ods.ods_cccc_erms_handle_dis_apply_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_handle_dis_apply_equ_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_out_lease_apply_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_out_settle_info_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_out_lease_list_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_own_test_detection_equipment_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_own_fixed_assets_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_own_depr_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_own_state_change_his_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_own_certificate_his_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_waf_core_attach_info_i_d drop partition (end_date <= '${etl_date}');
--纯新增表,没有做拉链表
alter  table ods.ods_cccc_erms_em_system_appcountinfo_i_d drop partition (etl_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_em_system_appcount_i_d drop partition (etl_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_deploy_dispatch_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_deploy_dispatch_equ_information_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_deploy_apply_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_deploy_apply_equ_i_d drop partition (end_date <= '${etl_date}');
alter  table ods.ods_cccc_erms_base_equ_subpack_i_d drop partition (end_date <= '${etl_date}');
truncate table ods.ods_cccc_erms_base_equ_tech_f_d;
truncate table ods.ods_cccc_erms_invm_plan_year_amountdet_f_d;
truncate table ods.ods_cccc_erms_invm_plan_pro_relation_f_d;
truncate table ods.ods_cccc_erms_out_lease_apply_relation_f_d;
truncate table ods.ods_cccc_erms_equip_type_mapping_f_d;
truncate table ods.ods_cccc_erms_act_ge_bytearray_f_d;
truncate table ods.ods_cccc_erms_act_ge_property_f_d;
truncate table ods.ods_cccc_erms_act_hi_actinst_f_d;
truncate table ods.ods_cccc_erms_act_hi_attachment_f_d;
truncate table ods.ods_cccc_erms_act_hi_comment_f_d;
truncate table ods.ods_cccc_erms_act_hi_detail_f_d;
truncate table ods.ods_cccc_erms_act_hi_identitylink_f_d;
truncate table ods.ods_cccc_erms_act_hi_procinst_f_d;
truncate table ods.ods_cccc_erms_act_hi_taskinst_f_d;
truncate table ods.ods_cccc_erms_act_hi_varinst_f_d;
truncate table ods.ods_cccc_erms_act_id_group_f_d;
truncate table ods.ods_cccc_erms_act_id_info_f_d;
truncate table ods.ods_cccc_erms_act_id_membership_f_d;
truncate table ods.ods_cccc_erms_act_id_user_f_d;
truncate table ods.ods_cccc_erms_act_procdef_relation_f_d;
truncate table ods.ods_cccc_erms_act_re_deployment_f_d;
truncate table ods.ods_cccc_erms_act_re_model_f_d;
truncate table ods.ods_cccc_erms_act_re_procdef_f_d;
truncate table ods.ods_cccc_erms_act_ru_event_subscr_f_d;
truncate table ods.ods_cccc_erms_act_ru_execution_f_d;
truncate table ods.ods_cccc_erms_act_ru_identitylink_f_d;
truncate table ods.ods_cccc_erms_act_ru_job_f_d;
truncate table ods.ods_cccc_erms_act_procdef_info_f_d;
truncate table ods.ods_cccc_erms_act_ru_task_f_d;
truncate table ods.ods_cccc_erms_act_ru_variable_f_d;
truncate table ods.ods_cccc_erms_act_task_opinion_f_d;
truncate table ods.ods_cccc_erms_waf_core_dict_f_d;
truncate table ods.ods_cccc_erms_waf_core_dictitem_f_d;
truncate table ods.ods_cccc_erms_waf_ac_organ_f_d;
truncate table ods.ods_cccc_erms_invm_plan_yeartime_f_d;
truncate table ods.ods_cccc_erms_waf_ac_organ2biz_f_d;
truncate table ods.ods_cccc_erms_zmdgs_actorginf_f_d;